### PR TITLE
Fix broken link to Secunia's blog post

### PR DESCRIPTION
**Pull request by JayAndCatchFire**
Flexera bought Secunia and redirected Secunia's blog to Flexera's blog, which doesn't contain the original Flexera blog post.  Replaced the effectively dead link to the archive.org copy.

### CODE REVIEW

**Comment by attritionorg** [comment]
Excellent. I wasn't good about making sure everything *was* on archive.org along the way. More recently I have gotten in the habit of using archive.today to take a quick snapshot. For those not familiar, there is also archive.ninja which was created by Dade after my general whining, which lets you one-click send it to both archive sites.

**Comment by JayAndCatchFire** [comment]
It appears archive.today doesn't have a copy: https://archive.ph/http://secunia.com/blog/shooting-the-messenger-372/

**Comment by sickcodes** [comment]
LGTM!

Instead of relying the archive, do you think you can push the file to the goodies folder since it's a chill txt file? Or even a PDF of the archived page to add additional authenticity since there are no email headers

**Comment by JayAndCatchFire** [comment]
Oh!  For `footnote 8.txt`.  I was so confused because I didn't change that link.

Yeah, I can add that.

**Comment by JayAndCatchFire** [comment]
I added a local copy of the file and linked to it in the README.  I also added a PDF for additional provenance, but I chose to link to the txt file since the pdf ruins some of the original formatting, including line breaks on links. 😞

**Comment by sickcodes** [comment]
Perfect addition to the collection! Yeah it's a bit messy currently, I was thinking about ways to clean it up, maybe proposing to transpose it into horizontal chunks later, not sure, maybe it's perfect the way it is. Thanks for the commits @JayAndCatchFire much appreciated

**Pull request merged**
