### PR TITLE
Add report about Apperta Foundation and Rob Dyke

### PR DESCRIPTION
**Pull request by robdyke**

### CODE REVIEW

**Comment by sickcodes** [comment]
Can you make it from a new PR so the merge block runs away?

**Comment by sickcodes** [comment]
Also put some documents in the goodies folder

**Comment by robdyke** [comment]
Will do

**Comment by sickcodes** [comment]
| 2021-03-06| [Apperta Foundation](https://apperta.org/)|[Rob Dyke](https://github.com/robdyke)|Secrets in public repositories|Security researcher had to launch GoFundMe campaign to fund legal costs defending civil and criminal threats over vulnerability disclosure - See [PortSwigger](https://portswigger.net/daily-swig/security-researcher-launches-gofundme-campaign-to-fight-legal-threat-over-vulnerability-disclosure) and Rob's [howto-disclose](https://robdyke.com/howto-disclose/) blog|

If u cbf syncing the forks just delete the fork and I saved it here for ya

**Comment by sickcodes** [comment]
I will manually add this incident unless @attritionorg wants to do the PR

**Comment by robdyke** [comment]
SYNC THE FORKS ROB, FFS
(Note to self)

**Comment by attritionorg** [comment]
> I will manually add this incident unless @attritionorg wants to do the PR

I added it, unless it got lost in a PR on the wrong branch. Can copy/paste from the Errata copy.

**Comment by sickcodes** [comment]
Oh yeah we also have different data @robdyke 

This will fix your fork rob
```bash
git clone git@github.com:robdyke/research-threats.git
cd research-threats
git remote add disclose https://github.com/disclose/research-threats.git
git checkout -f disclose/master
git push origin HEAD:master
```

**Comment by sickcodes** [comment]
```
<<<<<<< master
| 2021-03-06| [Apperta Foundation](https://apperta.org/)|[Rob Dyke](https://github.com/robdyke)|Secrets in public repositories|Security researcher had to launch GoFundMe campaign to fund legal costs defending civil and criminal threats over vulnerability disclosure - See [PortSwigger](https://portswigger.net/daily-swig/security-researcher-launches-gofundme-campaign-to-fight-legal-threat-over-vulnerability-disclosure) and Rob's [howto-disclose](https://robdyke.com/howto-disclose/) blog|
=======
| 2021-03-25 | [Apperta Foundation](https://apperta.org/) | [Rob Dyke](https://twitter.com/robdykedotcom/) | Sensitive Public Info | Dyke [discovered](https://twitter.com/robdykedotcom/status/1374667465955938306) that Apperta had sensitive information on their GitHub repo and informed them. Apperta [reported Dyke](https://twitter.com/robdykedotcom/status/1374667465955938306/photo/1) to the Northumbria Police department despite them making the serious error and him being a good citizen. They also [revoked the license](https://twitter.com/robdykedotcom/status/1374720875086413828) to the materials published under NHoS, which they funded, after [pledging full transparency](https://twitter.com/robdykedotcom/status/1374671205287002114) to other matters in years prior. Summary and more details [in BleepingComputer](https://www.bleepingcomputer.com/news/security/engineer-reports-data-leak-to-nonprofit-hears-from-the-police/). |
>>>>>>> master
```

**Comment by sickcodes** [comment]
Which one do we want?

**Comment by robdyke** [comment]
the second one is good

**Comment by sickcodes** [comment]
Merged.

Added that Apperta Foundation is Supported by NHS England, NHS Digital

**Pull request merged**
